server :
    port : 21000

# Banner
banner.location : classpath:banner.txt

spring:
  application:
    name: Driftsdashboard

  main :
      sources : springboot.admin.Application
  boot:
    admin:
        url: http://localhost:21000
        notify:
          mail :
            enabled : true
            to : "erik.nygren@online.no"
            from : "noreply@skatteetaten.no"
  mail :
    host : smtp.online.no
    username : erinygre

# vises i /info
info :
   id : spring-boot-admin
   version : @project.version@
   stage : test
   build :
      artifact : @project.artifactId@
      name : @project.name@
      description : @project.description@
      version : @project.version@